on: [push, pull_request]

jobs:
  cloud-maven-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          # cache: 'maven'
      - name: detect-app-version
        run: echo "XC_VER=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: print-app-version
        run: echo "Detected application version:" ${{ env.XC_VER }}
      - name: aws-config-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: aws-ecr-login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: maven-build
        run: mvn --batch-mode --update-snapshots package
      - name: docker-push-to-ecr
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: xoom-cloud-demo
          IMAGE_TAG: ${{ env.XC_VER }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f aws-demo/Dockerfile aws-demo
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG