on: [push, pull_request]

jobs:
  xoom-cloud-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          # cache: 'maven'
      - name: detect-app-version
        run: echo "XC_VER=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: print-app-version
        run: echo "Detected application version:" ${{ env.XC_VER }}
      - name: maven-build
        run: mvn --batch-mode --update-snapshots package
      - name: login-to-public-ecr
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1
      - name: docker-push-to-ecr
        run: |
          docker build -t public.ecr.aws/g9b2w1m3/xoom-cloud-demo:$XC_VER -f aws-demo/Dockerfile aws-demo
          docker push public.ecr.aws/g9b2w1m3/xoom-cloud-demo:$XC_VER